/**
 * Object keys for uploaded product images:
 * `products/<productId>/<random uuid>.<ext>`. Keys are generated by the
 * server only; the random part makes every upload a new immutable object, so
 * URLs can be cached forever and never collide.
 */

const UUID = "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}";
const PRODUCT_IMAGE_KEY = new RegExp(
  `^products/${UUID}/${UUID}\.(jpg|png|webp)$`,
);

export type StoredImageExtension = "jpg" | "png" | "webp";

export function productImageKey(
  productId: string,
  extension: StoredImageExtension,
): string {
  return `products/${productId.toLowerCase()}/${crypto.randomUUID()}.${extension}`;
}

/**
 * True for keys this application created in object storage. Other image rows
 * (e.g. development seed images served from /public) have no stored object
 * to delete.
 */
export function isManagedImageKey(key: string): boolean {
  return PRODUCT_IMAGE_KEY.test(key);
}

export const IMAGE_CONTENT_TYPES: Readonly<
  Record<StoredImageExtension, string>
> = {
  jpg: "image/jpeg",
  png: "image/png",
  webp: "image/webp",
};

export function contentTypeForKey(key: string): string | null {
  const extension = key.slice(key.lastIndexOf(".") + 1);
  return extension in IMAGE_CONTENT_TYPES
    ? IMAGE_CONTENT_TYPES[extension as StoredImageExtension]
    : null;
}
