import { z } from "zod";

import {
  cartConflictMessages,
  MAX_CART_LINES,
  MAX_LINE_QUANTITY,
  type CartConflict,
} from "@/lib/cart/cart";
import {
  unavailableMessages,
  type UnavailableReason,
} from "@/lib/cart/evaluate";
import { formatPrice, MAX_AMOUNT } from "@/lib/money";

/*
 * Checkout request/response contract between the cart drawer and
 * POST /api/checkout. Isomorphic: the browser builds requests and renders
 * failures with it; the server validates requests with the same schema.
 *
 * The browser sends only intent (product IDs and quantities), the prices it
 * displayed (`expectedUnitPriceAmount`) and a random attempt ID. The server
 * never charges a browser-supplied price: it compares the displayed price
 * with the current one and refuses the checkout if they differ, so the
 * customer never pays an amount they were not shown.
 */

export const checkoutLineSchema = z
  .object({
    productId: z.uuid(),
    quantity: z.number().int().min(1).max(MAX_LINE_QUANTITY),
    expectedUnitPriceAmount: z.number().int().min(0).max(MAX_AMOUNT),
  })
  .strict();

export const checkoutRequestSchema = z
  .object({
    /** Idempotency key: one per checkout attempt, generated by the browser. */
    attemptId: z.uuid(),
    /** The browser's previous attempt, released when a new one starts. */
    previousAttemptId: z.uuid().optional(),
    lines: z
      .array(checkoutLineSchema)
      .min(1)
      .max(MAX_CART_LINES)
      .refine(
        (lines) =>
          new Set(lines.map((line) => line.productId)).size === lines.length,
        "duplicate product",
      ),
  })
  .strict();

export type CheckoutLineRequest = z.infer<typeof checkoutLineSchema>;
export type CheckoutRequest = z.infer<typeof checkoutRequestSchema>;

/** Why one cart line cannot be checked out as requested. */
export type CheckoutIssue =
  | { productId: string; kind: "unavailable"; reason: UnavailableReason }
  | {
      productId: string;
      kind: "insufficient_quantity";
      availableQuantity: number;
    }
  | {
      productId: string;
      kind: "price_changed";
      unitPriceAmount: number;
      expectedUnitPriceAmount: number;
    };

export type CheckoutFailureCode =
  /** The cart must change first; see `issues` and `conflict`. */
  | "rejected"
  /** This attempt can no longer be used; start a new one. */
  | "attempt_closed"
  | "rate_limited"
  | "invalid_request"
  /** Stripe or the store configuration is unavailable. */
  | "payment_unavailable"
  /** Too much contention right now; retrying shortly is safe. */
  | "busy";

export type CheckoutResponse =
  | { ok: true; url: string }
  | {
      ok: false;
      code: "rejected";
      issues: CheckoutIssue[];
      conflict: CartConflict | null;
    }
  | { ok: false; code: Exclude<CheckoutFailureCode, "rejected"> };

export type CheckoutFailure = Extract<CheckoutResponse, { ok: false }>;

/** Stripe Hosted Checkout lives on this origin only. */
export const STRIPE_CHECKOUT_ORIGIN = "https://checkout.stripe.com";

/**
 * The browser follows a checkout URL only if it points at Stripe Hosted
 * Checkout over HTTPS, so a tampered or buggy response can never turn the
 * checkout button into an open redirect.
 */
export function isStripeCheckoutUrl(value: unknown): value is string {
  if (typeof value !== "string") return false;
  try {
    const url = new URL(value);
    return (
      url.origin === STRIPE_CHECKOUT_ORIGIN &&
      url.username === "" &&
      url.password === ""
    );
  } catch {
    return false;
  }
}

export const GENERIC_CHECKOUT_ERROR =
  "Det gick inte att starta betalningen. Försök igen.";

export type CheckoutFailureMessage = { title: string; details: string[] };

/**
 * Swedish explanation of a failed checkout. `nameOf` returns the product
 * name currently shown in the cart (or null when unknown).
 */
export function checkoutFailureMessage(
  failure: CheckoutFailure,
  nameOf: (productId: string) => string | null,
): CheckoutFailureMessage {
  switch (failure.code) {
    case "rejected":
      return rejectionMessage(failure, nameOf);
    case "rate_limited":
      return {
        title:
          "Du har gjort många försök på kort tid. Vänta några minuter och försök igen.",
        details: [],
      };
    default:
      return { title: GENERIC_CHECKOUT_ERROR, details: [] };
  }
}

function rejectionMessage(
  failure: Extract<CheckoutFailure, { code: "rejected" }>,
  nameOf: (productId: string) => string | null,
): CheckoutFailureMessage {
  const details = failure.issues.map((issue) => {
    const name = nameOf(issue.productId) ?? "En produkt";
    switch (issue.kind) {
      case "unavailable":
        return `${name}: ${unavailableMessages[issue.reason]}`;
      case "insufficient_quantity":
        return issue.availableQuantity === 0
          ? `${name}: Produkten finns inte längre i lager.`
          : `${name}: Det valda antalet finns inte tillgängligt. Det finns ${issue.availableQuantity} kvar.`;
      case "price_changed":
        return `${name}: Priset har ändrats från ${formatPrice(issue.expectedUnitPriceAmount)} till ${formatPrice(issue.unitPriceAmount)}.`;
    }
  });
  if (failure.conflict) details.push(cartConflictMessages[failure.conflict]);

  return {
    title:
      "Kundvagnen har ändrats. Kontrollera den och tryck på Till kassan igen.",
    details,
  };
}
