import { z } from "zod";

import { MAX_CART_LINES, MAX_LINE_QUANTITY } from "@/lib/cart/cart";
import { MAX_AMOUNT } from "@/lib/money";

/*
 * Validation of POST /api/checkout bodies (src/server/checkout). Kept apart
 * from ./checkout.ts, which the cart drawer imports, so the browser bundle
 * only receives these types and never Zod itself. The browser sends only
 * intent: product IDs, quantities, the prices it displayed and a random
 * attempt ID. Totals, shipping or any other field are refused (strict).
 */

export const checkoutLineSchema = z
  .object({
    productId: z.uuid(),
    quantity: z.number().int().min(1).max(MAX_LINE_QUANTITY),
    expectedUnitPriceAmount: z.number().int().min(0).max(MAX_AMOUNT),
  })
  .strict();

export const checkoutRequestSchema = z
  .object({
    /** Idempotency key: one per checkout attempt, generated by the browser. */
    attemptId: z.uuid(),
    /** The browser's previous attempt, released when a new one starts. */
    previousAttemptId: z.uuid().optional(),
    lines: z
      .array(checkoutLineSchema)
      .min(1)
      .max(MAX_CART_LINES)
      .refine(
        (lines) =>
          new Set(lines.map((line) => line.productId)).size === lines.length,
        "duplicate product",
      ),
  })
  .strict();

export type CheckoutLineRequest = z.infer<typeof checkoutLineSchema>;
export type CheckoutRequest = z.infer<typeof checkoutRequestSchema>;
